### ISSUE TITLE
Switching between lndhub accounts requires app restart

### ISSUE THREAD

**Issue by kirkawolff** [ZeusLN/zeus#1102]
Install three or more lndhub accounts into zeus with different balances to see whether switching works. Then try switching between them and see maybe the first one or two times works, bit then rapidly degrades, particularly after performing a payment. The only way to reliably switch accounts is to select the desired account, then go to "force stop" from the app info screen. Then when you restart the app you can see the correct balance and transaction history. Sometimes this is also required to get a ln payment to compelte with lndhub accounts.

**Comment by kaloudis** [comment]
Would love if you could test and see if this issue persists in v0.7.0

**Comment by kaloudis** [comment]
Closing due to inactivity. I think this has been addressed through some refactoring

**Comment by bota87** [comment]
I'm running v0.7.3 and the issue still persist for me. I have 2 accounts on the same lndhub, one with user invoice, the other with user admin
