### ISSUE TITLE
Cannot connect to a Spark Server (Core Lightning, Tor)

### ISSUE THREAD

**Issue by ghost** [ZeusLN/zeus#978]
### Describe the bug

I use Orbot to connect a mobile Spark wallet to a Spark Server, either scanning the QR code or manually typing the server URL and the API Access Key.

It doesn't work with Zeus.The app freezes and I'm forced to clear cache and storage.

### Reproduce

1. In Zeus v0.6.4: Connect a node - Spark (c-lightning)
2. Add host + access key
3. Use Tor - enabled
4. Does not connect. Freezes

* I can connect Zeus to an LND node, though. No issues wahatsoever using lndconnect and a Tor hidden service. 

### Zeus version

v0.6.2

### Network

Tor

### Device

Pixel 4a

### Device operating system

GrapheneOS

**Comment by kaloudis** [comment]
Spark uses RPC and I believe our built-in Tor process only supports REST. A workaround for now could be to use Orbot instead of our built-in process.

**Comment by kaloudis** [comment]
Addressing this here: https://github.com/ZeusLN/zeus/pull/984/files

You actually can use the built-in Tor process

**Comment by kobiebotha** [comment]
I'm experiencing the same issue on iOS, FWIW.

**Comment by kaloudis** [comment]
This is fixed in v0.6.5. We have rc1 out now.

**Comment by kobiebotha** [comment]
I'm still having this issue in rc2

# Setup
* CLN v0.11.0.1-34-g0153621
   *  compiled from source running on macOS Monterey
   * fully synced, peers connected, channel established
   * running over tor
* Zeus 0.6.5 rc-2 on iOS Testflight
* Spark wallet launched using `npx spark-wallet`
* Confirmed that Spark looks good over Tor Browser from another host

# Description of issue
* After configuring my node in Zeus and connecting, I get the red screen of death as shown in Screenshot 1
* In addition, I can see lots of red HTTP 500s in my Spark console - Screenshot 2

# Fix
* Running Zeus in Android Simulator provided a more useful screen of death - Screenshot 3, with similar red 500s in Spark console logs
* All three calls below in Zeus' `Wallet.tsx` were causing the 500s
```
            ChannelsStore.getChannels();
            FeeStore.getFees();
            NodeInfoStore.getNodeInfo();
```
* I determined that the function signature in the `rpc` method in the `Spark.ts` backend was being called differently when using the app versus using Tor Browser

Specifically, I changed this

`rpc = (rpcmethod: string, param = {}, range: any = null) => {`

to this

`rpc = (rpcmethod: string, param = [], range: any = null) => {`

and now the app works perfectly with green 200s in the Spark console - see screenshot 4

# Interpretation
What I can't understand is that nothing has changed recently between this rpc method in `Spark.ts` and the [associated code in Spark](https://github.com/shesek/spark-wallet/blame/112fd9bb835f4ee10feeeb46d6c6ebeb78db1c61/src/app.js#L52), which makes me think that perhaps this is some kind of edge case that @bisq-usr and I are running into? Let me know if I can be of any further assistance tracking this down.

# Screenshots

Screenshot 1
![IMG_A2F0631D58E7-1](https://user-images.githubusercontent.com/277659/173490987-7602793b-c512-42ca-b3ca-c3c74d3a2770.jpeg)

Screenshot 2
![image](https://user-images.githubusercontent.com/277659/173491271-1feb7139-e44c-4345-817a-d28c8ae3737b.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/277659/173491329-8c978da3-4e7d-4a3b-962d-0059361f6d65.png)

Screenshot 4
![image](https://user-images.githubusercontent.com/277659/173491688-8bd2704c-4e9c-40f8-8d7d-e6fbd7377648.png)

**Comment by kobiebotha** [comment]
Update:

rc3 has the same behavior as above.

I also tried disabling tor and connecting directly over my LAN - I get the same "no method" error (albeit slightly better formatted now).

I'm calling it a day, I'm just going to use CLN-Rest-API over VPN for now.

**Comment by sha-265** [comment]
It's happening over SSH also.

**Comment by kaloudis** [comment]
Closing this in favor of https://github.com/ZeusLN/zeus/issues/739

We're gonna hunt this down for a fix in v0.7.0
